name: build CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RELEASE_TYPE: ${{ inputs.release_type }}
  NEW_VERSION: ${{ inputs.new_version }}
  PLAYKIT_PREV_VERSION: ${{ inputs.playkit_prev_version }}
  DTG_DEP_VERSION: ${{ inputs.dtg_dep_version }}
  REPO_NAME: ${{ github.event.repository.name }}
  MODULE_NAME: "fbadsplugin"
  MY_SECRET: ${{ secrets.MY_SECRET }}

jobs:

  TestBuild:
    environment: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and clone to CI workspace
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: print log
        run: |
          git log --oneline
      
      - name: print log-1
        run: |
           git log 'v12.1.0'..'v25.1.0' --oneline 
          
      - name: print log-2
        run: |
          git log --oneline 'v12.1.0'..Head --grep='(#'
          
      - name: print log-3
        run: |
          git log --oneline 'v12.1.0'..Head --grep='(#' | cut -d' ' -f2-
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Android native build
        run: ./gradlew build
